### ISSUE TITLE
download SCPA failed

### ISSUE THREAD

**Issue by zpingfeng** [jackbibby1/SCPA#1]
> # install.packages("devtools")
> devtools::install_github("jackbibby1/SCPA")
Downloading GitHub repo jackbibby1/SCPA@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/jackbibby1/SCPA/tarball/HEAD' failed

**Comment by jackbibby1** [comment]
Hi. I think this may be an issue on your side. Do have you got the most recent devtools version? Someone seems to have had a similar issue here: https://stackoverflow.com/questions/65273115/r-devtoolsinstall-githubjzsbioinfo-aprd-error-in-utilsdownload-fileurl

**Comment by zpingfeng** [comment]
The SCPA was installed with the most recent devtools! Thank you very much!
