### ISSUE TITLE
missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by zpingfeng** [jackbibby1/SCPA#2]
Hi Jack,
I run compare_pathways with several lists generated with seurat_extract function (se obj), but it gave an error message shown that:  **Error in if (lowerpval < level) { : missing value where TRUE/FALSE needed**
I dont know how do I input the TRUE/FALSE . Could you please help? 

details:
> str(se[[1]])
 num [1:18347, 1:3989] 0.001 0.001 0.001 0.001 0.001 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:18347] "AL627309.1" "AL627309.5" "AP006222.2" "LINC01409" ...
  ..$ : chr [1:3989] "AAACCTGAGATATGCA-1_1" "AAACCTGAGGAGTTTA-1_1" "AAACCTGCAATCCGAT-1_1" "AAACCTGGTTCCATGA-1_1" ...
> scpaH.comp[[1]] <- compare_pathways(samples = list(se[[1]]), pathways = pathwaysH)
Conducting 2-sample test
  |=                                                 |   2%Error in if (lowerpval < level) { : missing value where TRUE/FALSE needed

> str(se[[2]])
 num [1:18347, 1:3200] 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:18347] "AL627309.1" "AL627309.5" "AP006222.2" "LINC01409" ...
  ..$ : chr [1:3200] "ACGCCAGCATGTCTCC-1_2" "AGCTCTCCAGCTCGCA-1_2" "ATCATGGTCATGGTCA-1_2" "CACACAAAGTCGTTTG-1_2" ...
> scpaH.comp[[2]] <- compare_pathways(samples = list(se[[2]]), pathways = pathwaysH)
Conducting 2-sample test
  |=                                                 |   2%Error in if (lowerpval < level) { : missing value where TRUE/FALSE needed

...

**Comment by jackbibby1** [comment]
Hi. It's difficult to tell from what you've sent, but it looks like you're maybe only supplying one population in the `compare_pathways()` function? Is `se` a list with a couple of data frames within it? Can you send me the code you're using to generate `se`? 

In the `compare_pathways()` comparison, you need to supply 2 or more populations to compare e.g.
```
scpa_out <- compare_pathways(samples = list(se[[1]], se[[2]]), pathways = pathwaysH)
```

**Comment by zpingfeng** [comment]
ok. I have 4 samples with 13 clusters. the i here is an indication of a cluster. I have tested  list(se[[1]], se[[2]]), it works, but it is not what I want. I will reorganise the data. Thank you very much !

**Comment by jackbibby1** [comment]
OK, sounds good. Just let me know if there's anything else

**Comment by zpingfeng** [comment]
the problem for me is that there are not enough cells or no cells in some  clusters  for some samples. the result from list(se[[1]], se[[2]]) is the comparison between cluster 1 and 2 from all the samples, which is also very useful.   I need to extract more information and play more. Thank you for developing such nice tool!
