### ISSUE TITLE
Interpreting SCPA results over multiple populations

### ISSUE THREAD

**Issue by Mahmoudy96** [jackbibby1/SCPA#21]
Hello, 

I'm trying to use this package to find significant pathways between multiple clusters of a dataset, however the result from running something like: 
`compare_seurat(seurat_object,group1="score.clusters",group1_population =c("1","2","3","4"), pathways = pathways)`
Returns the qvals, and pvalue/p.adjust for the returned pathways. How can I figure out how relevant each pathway is to each group of the population? I can't figure out what the Qval really means in this context, and if it's even possible to "assign" each pathway to a certain group.

Thanks.

**Comment by jackbibby1** [comment]
Hi,

The Qval in that comparison will tell you the pathway that is the most differentially regulated across all the clusters. I'm not sure what question you want to answer, but the multiple comparisons approach you're using is probably most useful when you have a known external variable that you're analyzing (multiple time points, pseudotime, disease severity etc.), where you want to look at which pathways change across this variable. Here you can define the question based on your external variable i.e. what pathway changes the most in the populations over time/cell differentiation/disease progression, like Figure 3A or 4A-B in [our paper here](https://www.cell.com/cell-reports/pdf/S2211-1247(22)01571-6.pdf). This approach won't let you assign a certain pathway to each population though. If you want to do that, then I would probably stick to a two-sample comparison and use a reference population to compare to. For example, we looked what metabolic pathways define different memory T cell populations, using naive T cells as a baseline sample in Figure 4K i.e. comparing naive T cells to Th1, naive T cells to Th2 etc. etc.

Jack

**Comment by Mahmoudy96** [comment]
Thank you for the answer. I'm mostly interested in pathway significance in one of my clusters, so comparing it one-by-one to the others sounds like a good approach.
