### ISSUE TITLE
Gene information SCPA

### ISSUE THREAD

**Issue by Youvika** [jackbibby1/SCPA#22]
Hi Jack, Awesome package. I love it and planning to use this package in my current project.
Already got some nice results.
 But I have a query. 
Could we have the gene information also of the perturbed pathways between conditions?
For eg, pathway 1 is changed between condition A Vs Condition B, in X cell type, so which genes are responsible for making that change?
If we get this information I am gonna recommend this amazing tool to my colleagues. 
Pardon me if you explained earlier.
Thanks in advance

_Originally posted by @Youvika in https://github.com/jackbibby1/SCPA/discussions/14#discussioncomment-4352936_

**Comment by jackbibby1** [comment]
Referenced in discussion #24
