### ISSUE TITLE
Trajectory is not rooted

### ISSUE THREAD

**Issue by lf96abc** [jackbibby1/SCPA#26]
Hi,
Thanks very much for this great package. I am trying to run the following on my own dataset:

> plot_dimred(model_n4, 
+             "pseudotime", 
+             pseudotime = calculate_pseudotime(model_n4), 
+             hex_cells = F,
+             plot_trajectory = T, 
+             size_cells = 1, alpha_cells = 0.8) + 
+   theme(aspect.ratio = 1)

However, I am getting this error message:
root cell or milestone not provided, trying first outgoing milestone_id
Using '1' as root
Error in if (node$tag == "span") { : argument is of length zero
In addition: Warning message:
In calculate_pseudotime(model_n4) :
  Trajectory is not rooted. Add a root to the trajectory using dynwrap::add_root(). This will result in an error in future releases.

I have tried using the naive_cd4.rds dataset provided but loading this object gives the following error:
Error in load("naive_cd4.rds") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning messages:
1: In readChar(con, 5L, useBytes = TRUE) :
  truncating string with embedded nuls
2: file ‘naive_cd4.rds’ has magic number 'X'
  Use of save versions prior to 2 is deprecated 

I would be very grateful for your help.

**Comment by jackbibby1** [comment]
Hi. 

Your error on the trajectory is: "Trajectory is not rooted. Add a root to the trajectory using dynwrap::add_root(). This will result in an error in future releases.". Looks like you probably need to add your trajectory root. This is an issue from the dyno package side and not SCPA, so you may be better asking them.

Ah, this is my fault on the site. To read the naive_cd4.rds data in, you need to run `naive_cd4 <- readRDS("naive_cd4.rds")`. 

Jack

**Comment by lf96abc** [comment]
Thank you!
