### ISSUE TITLE
Interpreting the SCPA output

### ISSUE THREAD

**Issue by min0609** [jackbibby1/SCPA#27]
Hi,
First of all, thank you for this wonderful tool. 
I would like to know in which direction the pathway changes when comparing two populations. I understood that the FC value is calculated as a comparison of population1 - population2. So, when I get the result using the command line below, can I interpret that apoptosis is more active in PTC cells than in follicular cells?

`Follicular_PTC <- compare_pathways(samples = list(Follicular, PTC), pathways = pathways)`

<img width="618" alt="image" src="https://user-images.githubusercontent.com/105622235/209264501-ae38a54c-3427-4b90-be06-26cfbc35ff59.png">

**Comment by jackbibby1** [comment]
Hi,

Hope it has been useful. Yup, in your example, genes of the apoptosis pathway will be slightly enriched in your PTC cells (2 is still a relatively low fold change, given that SCPA calculates a sum of LogFCs for each gene of the pathway). Your Qval suggests the pathway is quite different in the two conditions though, so I would interpret this as the pathway having an enrichment independent aspect of differential regulation between your populations, which is discussed a bit [here](https://jackbibby1.github.io/SCPA/articles/interpreting_scpa_output.html#which-output-values-should-you-use)

Jack

**Comment by min0609** [comment]
Thank you for your help!

I have another question. Could I identify the leading edge genes that represent the most differentially active genes in the two populations?

Thanks again in advance!

**Comment by jackbibby1** [comment]
At the minute, we don't have a defined way to do this. In our analysis to date, we just plot/visualise gene expression levels of the total pathway after testing with SCPA. I'd currently suggest doing this, which may actually give you a more balanced impression of the pathway activity anyway
