### ISSUE TITLE
SCPA for Spatial Visium Data

### ISSUE THREAD

**Issue by cathalgking** [jackbibby1/SCPA#28]
Can I run compare_seurat (or compare_sce) on a Seurat object that contains a 10x Visium dataset for pathway analysis? Within the Seurat object is 4 microscope images with accompanying assays. I also have the same thing in a SPE (SpatialExperiment) object, which is analogous to a SingleCellExperiment object.
<img width="476" alt="Screen Shot 2023-01-17 at 1 42 12 pm" src="https://user-images.githubusercontent.com/32261323/212801735-6998a926-fa93-47fd-8d41-0db0e9d6d744.png">

**Comment by jackbibby1** [comment]
Hi,

At the minute, `compare_seurat()` pulls data from the RNA assay in the Seurat object by default, as this is typically the normalized data, but I'll change this so you can specify the assay you want to pull data from (I'll also change the `seurat_extract()` function so you can do the same). The `compare_sce()` function pulls data from the "logcounts" assay by default, but you should be able to specify other assays if you have them.  You just need to use the `assay_name` parameter within `compare_sce()`.

Thanks for highlighting this though -- I'll add the functionality to `compare_seurat()`. In the meantime, you can still extract the expression matrices manually that you want to compare and use it in the `compare_pathways()` function.

Jack

**Comment by jackbibby1** [comment]
OK @cathalgking -- if you install the latest version of SCPA, you should now be able to select your assay that you want to compare e.g.

```
scpa_out <- compare_seurat(data,
                           assay = "Spatial",
                           group1 = "cell",
                           group1_population = c("x", "y"),
                           pathways = pathways)
```


Just let me know if anything isn't going smoothly, or if you have any more questions.

Jack

**Comment by cathalgking** [comment]
Thanks for that prompt update @jackbibby1 
I updated the version of SCPA and it worked accordingly. A query about the methods here-I am using the 'cell_type' meta-data column in my object to compare gene sets. That column contains 16 different cell types. Do I have to choose 2 of those for the 'group1_population' parameter? For now I am just choosing 2 at random ("T cells", "B cells") and running the code. Is there a way to get a more 'general view' of the pathways? The bench scientist I am working with simply said to 'have a look at the pathways, maybe KEGG'! Also, when running 'plot_heatmap()', the plot is a condensed heat map full of all the pathways found. Even, if I choose one of the pathways at random (2,661 of them) in spa_out with 'highlight_pathways =', it is difficult to see what workflow to follow. Have you any recommendations here? Thanks

**Comment by jackbibby1** [comment]
Ah, good to hear. 

Hmm, yeah, it makes it a bit difficult without having a specific question to ask. I guess you could choose a cell type as a baseline and then permute through all the other cells as a comparator (something like we did [here](https://jackbibby1.github.io/SCPA/articles/systematic_tissue_comparison.html#pathway-analysis-across-tissues). Keeping your baseline cell type constant across all comparisons will give you a decent broad overview of pathway activity across the cell types, even if it's relative to a specific cell. Something like this:

```
pathways <- msigdbr("Homo sapiens", category = "C2", subcategory = "CP:KEGG") %>%
  format_pathways()
cell_types <- grep(pattern = "T cells", x = unique(spatialIntegrated$cell_type), value = T, invert = T)
scpa_out <- lapply(cell_types, function(x) compare_seurat(spatialIntegrated, 
                                                          pathways = pathways,
                                                          assay = "Spatial",
                                                          group1 = "cell_type",
                                                          group1_population = c("T cells", x)))
```

I assume it would be good to use the spatial data a bit more though, so you could do something similar based on spatial organization e.g. define a baseline spatial area/cell_type and then permute cell types/distance gradually away from that.

Apologies -- I'm not sure I follow exactly what you're trying to do with the heatmap bit. The plot_heatmap() function will just plot all the values from the SCPA output, but you can filter these before you feed it into the function if you like e.g. `scpa_out %>% filter(qval > 2) %>% plot_heatmap()`. But I would just choose what pathway to highlight based on what you choose to follow up e.g. if you want to follow up on a glycolysis signature, then you can plot your heatmap summary across all cells and comparisons, and just highlight the glycolysis signature you initially found. Something like the heatmap in the COVID comparison [here](https://jackbibby1.github.io/SCPA/articles/disease_comparison.html#plotting-the-output).
