### ISSUE TITLE
when i installed the packages, it always failed😭

### ISSUE THREAD

**Issue by yinguoli0103** [jackbibby1/SCPA#30]
<img width="562" alt="截屏2023-01-20 10 45 58" src="https://user-images.githubusercontent.com/74188658/213607081-7abebf52-e174-4f4a-9b31-e494ba294871.png"
i chosed '3',at last,
<img width="566" alt="截屏2023-01-20 10 49 49" src="https://user-images.githubusercontent.com/74188658/213607569-b81b265e-f137-4d51-af36-efdb406b807e.png">
these dependency packages are not installed because they are not available?!
I don't know how to solve it!

**Comment by jackbibby1** [comment]
Hi,

Hmm, I'm not getting this on my side.

Are you running the latest version of R? And have you tried to install the required packages manually first i.e. `install.packages(c("latticeExtra", "interp", "Hmisc"))` -- does that work? And then go back to the crossmatch installation after restarting your R session.

You can also just try to run:

```
devtools::install_github("jackbibby1/SCPA")
```

To see if it installs OK.

Jack

**Comment by yinguoli0103** [comment]
Hi, jack!
   Thanks for your reply for my problems! I just referred to your advice and updated my R version to the latest version, and then i installed the required package "nbpMatching" manually, finally i runned installations, it successed!
   Thank you for your help! Chinese Spring festival is coming,Happy New Year, best wishes to you!

**Comment by jackbibby1** [comment]
Hi,

Ah, good. All the best, and happy new year too. 

Just let me know if there are any more issues.

Jack
