### ISSUE TITLE
downsample in compare_seurat

### ISSUE THREAD

**Issue by quyaingo** [jackbibby1/SCPA#34]
Hello,
I changed the default downsample from 500 to a different value, but the warning still stated "If greater than 500 cells, these populations will be downsampled".

Does this mean that the downsample parameter does not work?
Thank you in advance.

**Comment by jackbibby1** [comment]
Hi.

Are you running the latest version of SCPA? V1.5?

Jack

**Comment by quyaingo** [comment]
Yes, 1.5.0

**Comment by quyaingo** [comment]
Thanks a lot!

**Comment by jackbibby1** [comment]
Hi -- I've fixed the downsampling issue now, so things should be working properly. You just need to re-run the install so you're on v1.5.1

**Comment by quyaingo** [comment]
Great! It worked. Thank you!
