### ISSUE TITLE
combined_metabolic_pathways. csv for mice?

### ISSUE THREAD

**Issue by liyan910117** [jackbibby1/SCPA#37]
combined_metabolic_pathways. csv file is for humans only. Is there one for mice?

**Comment by jackbibby1** [comment]
Hi,

msigdb now contains all mouse identifiers for the pathways, so it's probably easiest to pull the pathway names from the combined_metabolic_pathways.csv file and use these to filter the msigdbr package. You can do this by:

```
library(msigdbr)
library(SCPA)
library(dplyr)

metab_paths <- read.csv("~/Downloads/combined_metabolic_pathways.csv", header = F)
metab_paths <- metab_paths$V1

mouse_metab <- msigdbr("Mus musculus") %>%
  filter(gs_name %in% metab_paths) %>%
  format_pathways()
```

Just let me know if there are any issues

Jack
