### ISSUE TITLE
Get genes associated with pathway terms

### ISSUE THREAD

**Issue by ayeTown** [jackbibby1/SCPA#38]
Hi there, 

Two questions. 
1) Is there a way to obtain the genes for each of the pathway terms after running the analysis?
2) After running the analysis I researched a couple of the terms and noticed they were associated with humans. However, I had run the analysis using mouse terms. Is this expected? Maybe the real issue is I don't understand the database well enough. 
My pathways were obtained as follows:

```
pathways <- bind_rows(msigdbr(species = "mouse",category = "H"),msigdbr(species = "mouse",category = "C2",subcategory = "CP:REACTOME"),msigdbr(species = "mouse",category = "C3",subcategory = "TFT:GTRD"),msigdbr(species = "mouse",category = "C5"))
```

As I said previously some of the resulting terms after running the analysis are actually human terms.

**Comment by ayeTown** [comment]
Thanks for responding so fast. So for the second question, below is a screenshot of the head of the results. The first pathway term is "ADNP_TARGET_GENES". If I look this up on the MSigDB side, the gene set is described as a human gene set: https://www.gsea-msigdb.org/gsea/msigdb/cards/ADNP_TARGET_GENES.html 

![image](https://user-images.githubusercontent.com/36680215/222519007-26821bdd-2a0d-48dd-9727-4642f04104fa.png)

**Comment by jackbibby1** [comment]
The msigdbr package was built on MSigDB v7.5.1 (see [here](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Release_Notes)), just before the addition of the mouse release. It looks like msigdbr uses a few different sources to convert human genes to the mouse homologues (see [here](https://igordot.github.io/msigdbr/articles/msigdbr-intro.html#details)), which means that when you extract "mouse gene sets", it will be effectively the human gene sets with converted gene names, which is why you see human gene sets. If you wanted to use the mouse specific gene sets with SCPA you can always download the actual mouse gene sets from [MSigDB mouse collections](https://www.gsea-msigdb.org/gsea/msigdb/mouse/collections.jsp) -- selecting the "gene symbols" version of the gmt file -- and use the .gmt filepath directly in the compare_pathways() function.

```
scpa_out <- compare_pathways(samples = list(pop1, pop2), 
                             pathways = "gene_sets/mh.all.v2022.1.Mm.symbols.gmt")
```

**Comment by jackbibby1** [comment]
Thinking about this... to make it easier, I'll add some more documentation to the SCPA gene set webpage about mouse gene sets and using .gmt files. I'll also likely add some functionality so you can specify the filepaths of multiple gmt files at the same time, which you can't currently do.

**Comment by jackbibby1** [comment]
(just FYI... if you go this way, you currently need to [delete the URL](https://jackbibby1.github.io/SCPA/articles/using_gene_sets.html#using-a-gmt-file) column from the .gmt file before you use it in SCPA

**Comment by jackbibby1** [comment]
An update: 

v1.5.2 should now handle raw gmt files downloaded straight from MSigDB. You can specify one or more filepaths of the gmt files that you want to use and SCPA will format and merge all the gmt files in your analysis. There's an example of how  to do this in the gene set tutorials [here](https://jackbibby1.github.io/SCPA/articles/using_gene_sets.html#using-a-gmt-file). Hopefully that should make it easier if people want to use the updated human or mouse gmt versions

**Comment by ayeTown** [comment]
The gmt file list specification for the pathways works well for me. I was wondering if there is an easy way to add a column to the results which identifies which gmt file the gene set originated from.

**Comment by ayeTown** [comment]
I just used a modified version of the `get_paths` function to obtain that information. Would be cool if you could add that in with the gmt file list option.

**Comment by jackbibby1** [comment]
Yup, I can work on including that information as an optional output. Happy to look at including your function if you want to submit a PR in the meantime

**Comment by jackbibby1** [comment]
Hi,

Yup, this is something that we've discussed for a while, but we haven't found a reasonable feature selection method that would be appropriate, given the complex analysis that SCPA performs. Like you mention, highlighting differentially expressed genes would be too simplistic, given that SCPA encompasses more than this. 

This is part of a broader discussion on how biological pathways should be interpreted, but my general advice for approaching this is to filter out any genes of your pathway that aren't expressed, visualise the rest of the pathway (e.g. summarised heatmap), and then use your biological knowledge to guide the interpretation of which sets of genes are likely important e.g. apex transcription factors, critical enzymes, or just unexpected genes. In the end, given that pathways encompass the coordinate expression of many genes, which SCPA is trying to capture, I think this nuanced approach may give you a more complete picture of the pathway activity (even if it seems like more work upfront).

This is something that is always being discussed though, so I can let you know if there's anything implemented in the future.

Jack
