### ISSUE TITLE
Systems level tissue comparison - issue

### ISSUE THREAD

**Issue by lbiavat1** [jackbibby1/SCPA#4]
Hi, I am having some issues downloading the dataset for the tutorial.
Everything else is working perfectly, but I think there may be an issue with the download link for the rds file.
Thank you so much.

**Comment by jackbibby1** [comment]
Hey. I've just had a look, and it looks like I can get access from my side. Can you send a screenshot of the error/issue that you're having?

**Comment by lbiavat1** [comment]
Thanks for the quick reply. I can download the dataset szabo_t_cell.rds, but there is only one subset and I can't really do SplitObject and move forward.

**Comment by jackbibby1** [comment]
Ah, yeah, apologies. There looks to have been an issue with the file upload -- only a fraction of the file ended up there. I'll upload the file again now and let you know when it's sorted

**Comment by jackbibby1** [comment]
I can only update the link on the SCPA site on Tuesday, but here's a temporary link to the data: https://drive.google.com/file/d/1-HJHfSMw5EBP02ZjTrbX7Pd_5eYGe1Zz/view?usp=sharing

That looks to have uploaded properly now

**Comment by jackbibby1** [comment]
Hi. I've change the link on the site now, you should be able to get access to the correct data file. I'll close this now, but just let me know if there are any other issues.

**Comment by lbiavat1** [comment]
Thank you so much!
