### ISSUE TITLE
Error in utils::download SCPA

### ISSUE THREAD

**Issue by deepdiver25** [jackbibby1/SCPA#43]
I'm trying to download SCPA as directed in the tutorial, but I keep getting errors. It looks like I'm unable to install crossmatch or multicross and then I encounter this:
<img width="1108" alt="Screenshot 2023-04-14 at 8 38 20 AM" src="https://user-images.githubusercontent.com/130767330/232059109-24475df1-ffc1-4f7d-af04-ad5d94d5f83e.png">

**Comment by jackbibby1** [comment]
Hi,

What output do you get when you run:

```
devtools::install_version("crossmatch", version = "1.3.1", repos = "http://cran.us.r-project.org")
devtools::install_version("multicross", version = "2.1.0", repos = "http://cran.us.r-project.org")
```

Jack

**Comment by deepdiver25** [comment]
<img width="1103" alt="Screenshot 2023-04-14 at 8 45 58 AM" src="https://user-images.githubusercontent.com/130767330/232060888-d25c34be-45e7-4672-b681-1cd7b339cf18.png">
<img width="1108" alt="Screenshot 2023-04-14 at 8 46 14 AM" src="https://user-images.githubusercontent.com/130767330/232060958-9a9dcc7a-0d51-4ef4-af69-2fd5c0e2276b.png">

**Comment by jackbibby1** [comment]
It looks like you need to install the other packages you're getting an error for. Can you try:

```
install.packages(c("Hmisc", "checkmate", "htmlTable", "nbpMatching"))
```

And then run

```
# install.packages("devtools")
devtools::install_version("crossmatch", version = "1.3.1", repos = "http://cran.us.r-project.org")
devtools::install_version("multicross", version = "2.1.0", repos = "http://cran.us.r-project.org")
devtools::install_github("jackbibby1/SCPA")
```

**Comment by jackbibby1** [comment]
Ah, actually -- it also looks like you don't have the Xcode command line tools. You'll need this installed. If you open Terminal and run:

```
xcode-select --install
```

Then this should install them

**Comment by deepdiver25** [comment]
Thank you for your help, I needed to install xcode, the packages listed above and also complexheatmap, but I finally got there!
