### ISSUE TITLE
Package Installation Issues

### ISSUE THREAD

**Issue by shamer3** [jackbibby1/SCPA#44]
Having some issues getting the required packages installed for use of SCPA.
I have provided the error/console output I get below:

> library(devtools)
> library(usethis)
> devtools::install_version("crossmatch", version = "1.3.1", repos = "http://cran.us.r-project.org")
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/crossmatch/crossmatch_1.3-1.tar.gz
Installing 1 packages: nbpMatching
Installing package into ‘/Users/shamer/Library/R/x86_64/4.2/library’
(as ‘lib’ is unspecified)
trying URL 'http://cran.us.r-project.org/src/contrib/nbpMatching_1.5.1.tar.gz'
Content type 'application/x-gzip' length 28872 bytes (28 KB)
==================================================
downloaded 28 KB

* installing *source* package ‘nbpMatching’ ...
** package ‘nbpMatching’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c fcorematch.f -o fcorematch.o
make: gfortran: No such file or directory
make: *** [fcorematch.o] Error 1
ERROR: compilation failed for package ‘nbpMatching’
* removing ‘/Users/shamer/Library/R/x86_64/4.2/library/nbpMatching’
Warning: installation of package ‘nbpMatching’ had non-zero exit status
The downloaded source packages are in
	‘/private/var/folders/xm/20f92wf10jbd384g6g_ygnljph81s4/T/Rtmpzsd8Hu/downloaded_packages’
Installing package into ‘/Users/shamer/Library/R/x86_64/4.2/library’
(as ‘lib’ is unspecified)
ERROR: dependency ‘nbpMatching’ is not available for package ‘crossmatch’
* removing ‘/Users/shamer/Library/R/x86_64/4.2/library/crossmatch’
Warning: installation of package ‘/var/folders/xm/20f92wf10jbd384g6g_ygnljph81s4/T//Rtmpzsd8Hu/remotes897722f9d578/crossmatch’ had non-zero exit status
> devtools::install_version("multicross", version = "2.1.0", repos = "http://cran.us.r-project.org")
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/multicross/multicross_2.1.0.tar.gz
Skipping 1 packages not available: crossmatch
Installing 2 packages: crossmatch, nbpMatching
Installing packages into ‘/Users/shamer/Library/R/x86_64/4.2/library’
(as ‘lib’ is unspecified)
Warning: package ‘crossmatch’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagestrying URL 'http://cran.us.r-project.org/src/contrib/nbpMatching_1.5.1.tar.gz'
Content type 'application/x-gzip' length 28872 bytes (28 KB)
==================================================
downloaded 28 KB

* installing *source* package ‘nbpMatching’ ...
** package ‘nbpMatching’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c fcorematch.f -o fcorematch.o
make: gfortran: No such file or directory
make: *** [fcorematch.o] Error 1
ERROR: compilation failed for package ‘nbpMatching’
* removing ‘/Users/shamer/Library/R/x86_64/4.2/library/nbpMatching’
Warning: installation of package ‘nbpMatching’ had non-zero exit status
The downloaded source packages are in
	‘/private/var/folders/xm/20f92wf10jbd384g6g_ygnljph81s4/T/Rtmpzsd8Hu/downloaded_packages’
Installing package into ‘/Users/shamer/Library/R/x86_64/4.2/library’
(as ‘lib’ is unspecified)
ERROR: dependencies ‘nbpMatching’, ‘crossmatch’ are not available for package ‘multicross’
* removing ‘/Users/shamer/Library/R/x86_64/4.2/library/multicross’
Warning: installation of package ‘/var/folders/xm/20f92wf10jbd384g6g_ygnljph81s4/T//Rtmpzsd8Hu/remotes897720e15305/multicross’ had non-zero exit status
> devtools::install_github("jackbibby1/SCPA")
Downloading GitHub repo jackbibby1/SCPA@HEAD
Skipping 6 packages not available: singscore, GSVA, GSEABase, SummarizedExperiment, multicross, ComplexHeatmap
── R CMD build ───────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/xm/20f92wf10jbd384g6g_ygnljph81s4/T/Rtmpzsd8Hu/remotes89775879762f/jackbibby1-SCPA-495cacd/DESCRIPTION’ ...
─  preparing ‘SCPA’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘SCPA/inst/rds_files/th1_tcm.rds’
─  building ‘SCPA_1.5.2.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/Users/shamer/Library/R/x86_64/4.2/library’
(as ‘lib’ is unspecified)
ERROR: dependency ‘multicross’ is not available for package ‘SCPA’
* removing ‘/Users/shamer/Library/R/x86_64/4.2/library/SCPA’
Warning: installation of package ‘/var/folders/xm/20f92wf10jbd384g6g_ygnljph81s4/T//Rtmpzsd8Hu/file8977e3e350a/SCPA_1.5.2.tar.gz’ had non-zero exit status

**Comment by jackbibby1** [comment]
Hi @gt7901b,

This was an issue with Xcode not being installed, which is needed for installation of some R packages. You need to run:

```
xcode-select --install
```

Jack

**Comment by gt7901b** [comment]
Thanks for your prompt response, @jackbibby1 . Issue solved.  A note to others, use 
install_github('jokergoo/ComplexHeatmap')  instead of BioC to install ComplexHeatmap
