### ISSUE TITLE
Pseudobulking 

### ISSUE THREAD

**Issue by Nusob888** [jackbibby1/SCPA#47]
Hi Jack, 

In terms of the statistical approach, I want to check whether it is possible to use pseudo-bulked normalised count matrices and that this doesn't violate any of SCPA's assumptions? 

On a similar spectrum, could one use meta cell approaches such as [SEACells](https://doi.org/10.1038/s41587-023-01716-9)

**Comment by jackbibby1** [comment]
Hi Bo. Just echoing Divyansh, but also to add that I haven't really tested SCPA with pseudobulked data, so would be interested to see what you find if you want to share your analysis
