### ISSUE TITLE
SCT vs RNA assay with a Seurat Object

### ISSUE THREAD

**Issue by troks27** [jackbibby1/SCPA#53]
Another quick question Jack. Do you recommend using the SCT assay as derived from the Seurat SCTransform V2 workflow over the standard RNA assay? Will using the SCT assay impact any of the outputs from SCPA?

**Comment by jackbibby1** [comment]
Hi,

I haven't done a large comparison of the RNA versus SCT assays for SCPA, but SCPA can handle any data type (as long as it makes biological sense). So in theory, either the SCT or RNA assay should be good to use, though I would probably err on the side of using the RNA assay. For consistency, in our paper, we used the NormalizeData(..., normalization.method = "LogNormalize") function from Seurat throughout, but here's a small comparison of the two normalisation methods showing that they give pretty similar results (a bit of difference at the lower qvals).

```
library(SCPA)
library(Seurat)
library(tidyverse)
library(msigdbr)

# sctransform -------------------------------------------------------------
df <- readRDS("~/My Drive/example_datasets/naive_cd4.rds")
df <- UpdateSeuratObject(df)
df <- SCTransform(df)

# get data from RNA and SCT -----------------------------------------------
rna <- lapply(c(0, 24), function(x) seurat_extract(df, meta1 = "Hour", value_meta1 = x))
sct <- lapply(c(0, 24), function(x) seurat_extract(df, assay = "SCT", meta1 = "Hour", value_meta1 = x))

# get pathways ------------------------------------------------------------
pathways <- c("hallmark", "kegg")
pathways <- msigdbr("Homo sapiens") %>%
  filter(grepl(paste(pathways, collapse = "|"), gs_name, ignore.case = T)) %>%
  format_pathways()

# comparison of rna and sct -----------------------------------------------
rna <- compare_pathways(rna, pathways, parallel = T, cores = 3)
sct <- compare_pathways(sct, pathways, parallel = T, cores = 3)

plot(rna$qval, sct$qval, 
     xlab = "RNA qval", ylab = "SCT qval",
     bg = "#3498eb50", pch = 21, cex = 1.5)

```

<img src="https://github.com/jackbibby1/SCPA/assets/59352321/2b3bc512-1af0-4ae9-aa35-0e00c88107c5" width="400">
