### ISSUE TITLE
can't install SCPA package

### ISSUE THREAD

**Issue by BartBryant** [jackbibby1/SCPA#54]
Hi 
I get errors when trying to install SCPA package following 
https://jackbibby1.github.io/SCPA/index.html

i update R
i tried the other commands from previous 'issues'
install.packages(c("Hmisc", "checkmate", "htmlTable", "nbpMatching"))
# then try to install SPCA again

below error message

ERROR: dependencies ‘clustermole’, ‘ComplexHeatmap’, ‘multicross’, ‘SummarizedExperiment’ are not available for package ‘SCPA’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/SCPA’
Warning messages:
1: packages ‘singscore’, ‘GSVA’, ‘GSEABase’, ‘SummarizedExperiment’, ‘multicross’, ‘ComplexHeatmap’ are not available for this version of R

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In i.p(...) :
  installation of package ‘clustermole’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/var/folders/vt/ry7dn7kj7011ns0x1f86g2m40000gn/T//RtmpgWBqD7/file1e8154a2d265/SCPA_1.5.3.tar.gz’ had non-zero exit status
> library(SCPA)
Error in library(SCPA) : there is no package called ‘SCPA’

**Comment by jackbibby1** [comment]
Hi,

It looks like you may need to install the packages mentioned in your error manually e.g.

```
packages <- c("clustermole", "ComplexHeatmap", "SummarizedExperiment", "singscore", "GSVA", "GSEABase")
BiocManager::install(packages)
devtools::install_version("multicross", version = "2.1.0", repos = "http://cran.us.r-project.org")

```

Then restart R, and try to install SCPA again

Just let me know if that doesn't work

Jack

**Comment by BartBryant** [comment]
Hi Jack

that worked, thx

if i have other questions do you want me to start another 'issue' or continue with this thread?

**Comment by jackbibby1** [comment]
Good good. Yeah, if there's something else that comes up then just open a separate issue. I'll close this one now
