### ISSUE TITLE
SCPA comparsion (seurat object)

### ISSUE THREAD

**Issue by BartBryant** [jackbibby1/SCPA#55]
Hi 

Goal is to compare pathways in cell types in a Seurat object following 
https://jackbibby1.github.io/SCPA/articles/seurat_comparison.html

The seurat object contains two samples integrated via FindIntgrationsAnchor() 

up to the 'SCPA comparison' section, i get an error message (screenshot below)
thx in advance

<img width="1512" alt="Screenshot 2023-08-04 at 3 30 44 PM" src="https://github.com/jackbibby1/SCPA/assets/135715545/7498c71f-2d09-44ee-b465-aae8e8bbce2c">

**Comment by BartBryant** [comment]
sorry
actually figured it out by assessing my Seurat Object and finding the correct column name, which in this instance is called 'celltype.Lmod1'
<img width="1512" alt="Screenshot 2023-08-04 at 3 48 24 PM" src="https://github.com/jackbibby1/SCPA/assets/135715545/97bf0ca0-1fe5-492a-8930-9713dc319950">

**Comment by BartBryant** [comment]
also viewed my 'scpa_out' but unsure on ranking
in this example is 'HALLMARK_MYOGENESIS' higher in 'SMC_CTRL' or 'SMCs_mut'?

<img width="1512" alt="Screenshot 2023-08-04 at 3 50 25 PM" src="https://github.com/jackbibby1/SCPA/assets/135715545/ef3b15a4-07bd-4630-938f-fbc5720c67b4">

**Comment by jackbibby1** [comment]
Hi,

If you look at `?compare_seurat` there's a longer explanation under the value header, but the fold change (FC) column is calculated from population1 - population2. So that's CTRL-mut in your example i.e. higher in your CTRL condition.

Jack

**Comment by BartBryant** [comment]
so i assume you can do the inverse by switching the order? for example, to find out highest pathways in mutant, I would list it 'mut-CTRL' over 'CTRL-mut'?

also, can we determine which genes give rise to that type of pathway enrichment score?

Bart

**Comment by jackbibby1** [comment]
Maybe I'm missing the question, but SCPA calculates the fold changes in both directions anyway. Your FC column contains both positive and negative values, so the negative values are the pathways enriched in your "mut" condition.

There's a bit of a discussion [here](https://github.com/jackbibby1/SCPA/discussions/24#discussioncomment-4354254) around why it's quite difficult to identify particular genes driving the signature in SCPA and I would still recommend doing the same thing that I mentioned

**Comment by BartBryant** [comment]
thanks for the clarification on FC
and
info on why it is difficult to identify genes driving the signature in SCPA
