### ISSUE TITLE
Cannot run load the SCPA library

### ISSUE THREAD

**Issue by LilianGomes** [jackbibby1/SCPA#58]
I am having an issue when I try to load the library. I already installed it according to the tutorial and had not problem with it. 
```
# install.packages("devtools")
devtools::[install_version](https://remotes.r-lib.org/reference/install_version.html)("crossmatch", version = "1.3.1", repos = "http://cran.us.r-project.org")
devtools::[install_version](https://remotes.r-lib.org/reference/install_version.html)("multicross", version = "2.1.0", repos = "http://cran.us.r-project.org")
devtools::[install_github](https://remotes.r-lib.org/reference/install_github.html)("jackbibby1/SCPA")
```
However when I try to run the following error occurs:
```
> library(SCPA)
Error in library(SCPA) : there is no package called ‘SCPA’

```

**Comment by jackbibby1** [comment]
Hi,

Just double check the code above to make sure you actually ran this (i.e. without the square brackets and html code that is in your code above):

```
# install.packages("devtools")
devtools::install_version("crossmatch", version = "1.3.1", repos = "http://cran.us.r-project.org")
devtools::install_version("multicross", version = "2.1.0", repos = "http://cran.us.r-project.org")
devtools::install_github("jackbibby1/SCPA")
```

Can you run `devtools::install_github("jackbibby1/SCPA")` and send me the output?

Thanks
Jack

**Comment by LilianGomes** [comment]
Thank you! Now it worked!

**Comment by bdiluccia** [comment]
Hi,
I have the same problem Lilian had. I also ran what you suggested but still unable to install SCPA. 
Can you help me to fix it? Thank you!

**Comment by jackbibby1** [comment]
Hi,

Can you send me the error you're getting when you try to install?

Thanks
Jack

**Comment by bdiluccia** [comment]
sure! This is what I get:

> devtools::install_github("jackbibby1/SCPA")
Downloading GitHub repo jackbibby1/SCPA@HEAD
Skipping 6 packages not available: singscore, GSVA, GSEABase, SummarizedExperiment, multicross, ComplexHeatmap
Installing 6 packages: singscore, GSVA, GSEABase, SummarizedExperiment, ComplexHeatmap, clustermole
Warning: dependencies ‘GSEABase’, ‘GSVA’, ‘singscore’ are not available
installing the source package ‘clustermole’

trying URL 'https://cran.rstudio.com/src/contrib/clustermole_1.1.0.tar.gz'
Content type 'application/x-gzip' length 1298322 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

ERROR: dependencies ‘GSEABase’, ‘GSVA’, ‘singscore’ are not available for package ‘clustermole’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/clustermole’

The downloaded source packages are in
	‘/private/var/folders/lc/8yh0j6nj3m57cwk08mdc8lq00000gn/T/RtmpPFYmrx/downloaded_packages’
── R CMD build ────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/lc/8yh0j6nj3m57cwk08mdc8lq00000gn/T/RtmpPFYmrx/remotes5e9a6717b7ce/jackbibby1-SCPA-bb37ec7/DESCRIPTION’ (359ms)
─  preparing ‘SCPA’: (404ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘SCPA/inst/rds_files/th1_tcm.rds’
─  building ‘SCPA_1.5.4.tar.gz’
   
ERROR: dependencies ‘clustermole’, ‘ComplexHeatmap’, ‘singscore’, ‘SummarizedExperiment’ are not available for package ‘SCPA’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/SCPA’
Warning messages:
1: packages ‘singscore’, ‘GSVA’, ‘GSEABase’, ‘SummarizedExperiment’, ‘ComplexHeatmap’ are not available for this version of R

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In i.p(...) :
  installation of package ‘clustermole’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/var/folders/lc/8yh0j6nj3m57cwk08mdc8lq00000gn/T//RtmpPFYmrx/file5e9abc3708/SCPA_1.5.4.tar.gz’ had non-zero exit status

**Comment by jackbibby1** [comment]
Thanks. Can you try running:

```
BiocManager::install(c("clustermole", "ComplexHeatmap", "SummarizedExperiment", "singscore"))
```

Then restarting R, and try installing SCPA again:

```
devtools::install_github("jackbibby1/SCPA")
```

**Comment by bdiluccia** [comment]
It worked perfectly!!! 
Thank you very much
