### ISSUE TITLE
Cannot install SCPA Successfully

### ISSUE THREAD

**Issue by shamer3** [jackbibby1/SCPA#59]
I have previously worked with this package but I am now having issues with installing the SCPA package.
Conducting the install as described and I get the following output messages:

```
> devtools::install_version("crossmatch", version = "1.3.1", repos = "http://cran.us.r-project.org")
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/crossmatch/crossmatch_1.3-1.tar.gz
Installing package into ‘/Users/shamer/Library/R/x86_64/4.3/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘crossmatch’ ...
** package ‘crossmatch’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (crossmatch)
> devtools::install_version("multicross", version = "2.1.0", repos = "http://cran.us.r-project.org")
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/multicross/multicross_2.1.0.tar.gz
Skipping 1 packages not available: crossmatch
Installing package into ‘/Users/shamer/Library/R/x86_64/4.3/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘multicross’ ...
** package ‘multicross’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (multicross)
> devtools::install_github("jackbibby1/SCPA")
Downloading GitHub repo jackbibby1/SCPA@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/jackbibby1/SCPA/tarball/HEAD' failed
```

It appears the install of multi cross is skipping crossmatch for some reason although it looks as those it has installed properly.

Any help ?

**Comment by jackbibby1** [comment]
Hi,

The multicross and crossmatch installations are fine there -- the skipping message is just letting you know that it can't find the crossmatch package when trying to install multicross (because it's archived on CRAN).

I'm not completely sure on what's going on with the error. The installation runs fine on my end. Are you using Windows? Maybe [this discussion](https://github.com/forestgeo/learn/issues/102) or [this discussion](https://github.com/facebookincubator/GeoLift/issues/53) is helpful?

Jack

**Comment by shamer3** [comment]
Hi Jack,

No I am working with MacOS (intel chip), it worked perfectly before so Im not sure why not it isn't working.
I have tried both these solutions and neither have worked.

**Comment by jackbibby1** [comment]
Hmm -- I re-ran the installation from my end on a fresh environment this morning and it looks fine again. It may be an issue from the GitHub side, but I'm not really sure. I'll commit an update to the SCPA GitHub page, so can you try the install again now and see if that works?
