### ISSUE TITLE
Issue with "homemade" .csv file

### ISSUE THREAD

**Issue by AlexisFon** [jackbibby1/SCPA#60]
Hi, 

When I tried to run the compare pathways with an "homemade" .csv file for my pathways, I got this error : 

Generating gene sets from:
/Users/alexis/Documents/Doctorat/Project Single-Cell/Bioinformatics/Single-Cell Analysis/R/Inputs/Cell_Death_Pathways.csv
Cell numbers in population 1 = 1276
Cell numbers in population 2 = 825
If greater than 500 cells, these populations will be downsampled
**Error in pathways[keep_pathway] : invalid subscript type 'list'**
> 
**To Reproduce**

```
Pathways = "/Users/alexis/Documents/Doctorat/Project Single-Cell/Bioinformatics/Single-Cell Analysis/R/Inputs/Cell_Death_Pathways.csv"
Healthy_74 <- compare_pathways(samples = list(Healthy, Macro_CHU74), pathways = Pathways, min_genes = 5, parallel = T, cores = 4)
```

**Screenshots**
Here is my .csv file
![image](https://github.com/jackbibby1/SCPA/assets/141238205/74404c3c-36c4-4039-8c71-1abf935db399)

**Additional context**
[Cell_Death_Pathways.csv](https://github.com/jackbibby1/SCPA/files/13425145/Cell_Death_Pathways.csv)

Do you have an idea of the problem source ?

**Comment by jackbibby1** [comment]
Hi,

When I look at the csv file, it looks like this...

```
df <- read.csv("~/Downloads/Cell_Death_Pathways.csv")
head(df)
```
<img width="1344" alt="Screenshot 2023-11-21 at 08 32 38" src="https://github.com/jackbibby1/SCPA/assets/59352321/83f505c2-49bc-4cd4-9379-cfed54a032cd">

...
It's a ";" separated file, not csv. You could run this to format the file properly...

```
read.delim("~/Downloads/Cell_Death_Pathways.csv", sep = ";") %>%
  write.csv("~/Downloads/Cell_Death_Pathways_edited.csv", row.names = F)

Pathways <- "~/Downloads/Cell_Death_Pathways_edited.csv"
Healthy_74 <- compare_pathways(samples = list(Healthy, Macro_CHU74), pathways = Pathways, min_genes = 5, parallel = T, cores = 4)
```

Hopefully that works

Jack

**Comment by AlexisFon** [comment]
Indeed, it is working ! Thank you a lot. 

I have two additional questions : 
1. It is stated "This means that with SCPA you’re able to detect 1) enriched pathways and 2) non-enriched pathways that have transcriptional changes that are independent of enrichment." 
I don't really understand the second part, how those transcriptional changes are detected between two or more populations ? 
2. When comparing different clusters for example with the compare_seurat function, we end up with an object with the pathways and the qval for each pathway. If I understood well, higher the value, higher the difference of the pathway between the different clusters. Is that right ? And Is it possible to know where are the differences ? For instance, the two clusters where the in between difference is the highest ? Or do we have in this case, to perform all the two-by-two comparisons ? 
<img width="728" alt="image" src="https://github.com/jackbibby1/SCPA/assets/141238205/709166c1-68db-4b85-b18c-ed7a93ae6263">

**Comment by jackbibby1** [comment]
Good good.

If you're wanting to understand more about how SCPA generates it's results, I would encourage you to read our paper in [JASA](https://www.tandfonline.com/doi/full/10.1080/01621459.2020.1791131), or the discussion in our [Cell Reports paper](https://www.cell.com/cell-reports/fulltext/S2211-1247(22)01571-6#secsectitle0075). But briefly, something like the glycolysis pathway being stable in one condition (e.g. healthy) and highly variable in another (e.g. disease), even if there's not overall enrichment of the pathway in any condition, will be flagged by SCPA.

Yes, the higher the Qval, the higher the pathway difference. I would perform your test with SCPA in a way that is best answering the question you want. You don't want to use SCPA to just test across all cell types in your data like you have done above, because it won't tell you very much - it'll just tell you that there's a difference between your cell types. I would think about what question you want to ask e.g. how is cluster 1 different to cluster 4, or how is cluster 1 in the healthy condition different to cluster 1 in the disease, and then use those conditions as an input. You mainly want to use the multisample functionality if you have some sensible continuous-like data e.g. testing cluster 3 across 4 time points, or across healthy, mild, and severe disease, or testing differentiation of a cell type across a pseudotime trajectory

**Comment by thdk13** [comment]
Hi @jackbibby1,
I encountered the similar error when dealing with the 'homemade'.csv file. I got this error :
Error in x$Pathway : $ operator is invalid for atomic vectors
My code is like that:
`rest_act <-  compare_seurat(tumor,
                            group1 = "Harmonyclusters", 
                            group1_population = c("4","5","6"),
                            pathways = pathway_list,min_genes = 5, parallel = T, cores = 4)`
When I check the input csv file in R data, it is like this:
![image](https://github.com/jackbibby1/SCPA/assets/46933550/7610d2e8-c729-41c1-99ff-cdce16a0550b)
[cluster6_SCPA_input.csv](https://github.com/jackbibby1/SCPA/files/13498166/cluster6_SCPA_input.csv)
Could you help to check it? Thank you

**Comment by jackbibby1** [comment]
Hi @thdk13,

I'm not completely sure where the error is coming from here. Your pathway list runs fine from my end using the dataset from the tutorials [here](https://drive.google.com/file/d/1XstWBD4lOY0QNd-8Wzeh1f3-uYKuUU5Q/view). 

When I run:

```
df <- readRDS("naive_cd4.rds")
pathways <- get_paths("~/Downloads/cluster6_SCPA_input.csv")
scpa_out <- compare_seurat(df, group1 = "Hour", group1_population = c("0", "12"), pathways = pathways)

######## output...
scpa_out <- compare_seurat(df, group1 = "Hour", group1_population = c("0", "12"), pathways = pathways, min_genes = 5)
Extracting cells where Hour == 0
Extracting data from the RNA assay
Extracting cells where Hour == 12
Extracting data from the RNA assay
Using single core processing. Specify 'parallel = TRUE' and `cores = x` arguments for parallel processing

Cell numbers in population 1 = 4428
Cell numbers in population 2 = 4547
- If greater than 500 cells, these populations will be downsampled

Excluding 44 pathway(s) based on min/max genes parameter: Activation_of_NMDA_receptors_and_postsynaptic_events, Activation_of_anterior_HOX_genes_in_hindbrain_during_early_embryogenesis, Aggrephagy, Amyotrophic_Lateral_Sclerosis_Signaling, Apoptotic_execution_phase...

Calculating pathway fold changes...

Performing a two-sample analysis with SCPA...
  |==================================================| 100%


head(scpa_out)
                                          Pathway         Pval      adjPval     qval         FC
1 Processing_of_Capped_Intron-Containing_Pre-mRNA 1.486214e-32 9.660388e-31 5.478595 -10.086274
2                 RNA_Polymerase_II_Transcription 1.486214e-32 9.660388e-31 5.478595  -4.081617
3                          Mitotic_G2-G2.M_phases 1.229458e-31 7.991474e-30 5.394198  -4.004756
4                                 Cilium_Assembly 7.649358e-30 4.972083e-28 5.225271  -2.224025
5                 Coronavirus_Replication_Pathway 7.649358e-30 4.972083e-28 5.225271  -2.891381
6      Ribonucleotide_Reductase_Signaling_Pathway 7.649358e-30 4.972083e-28 5.225271  -1.872255
```

Can you run this to see if there are any errors:

```
test <- lapply(c("4","5","6"), function(x) seurat_extract(tumor, meta1 = "Harmonyclusters", value_meta1 = x))
test <- SCPA::pathway_matrices(samples = test, pathways = pathways)
```

Jack

**Comment by thdk13** [comment]
hi @jackbibby1 
Thank you for your reply. I found that it was my mistake when I directly input the pathway list in a csv file into R object data, not a path likes the tutorial. Now it works well. 
 I have a question regarding the interpretation of the results in the paper, specifically Figure 3D. As far as I understand, this heatmap illustrates the changes in cytokine responses across three time points for all four samples. I am curious if it is possible to generate a similar heatmap for just one time point, allowing us to discern the differences in cytokine responses within each sample, such as at 12 hours.
Returning to my own data, I aim to compare pathway activity across three clusters in the tumor (clusters 4, 5, and 6). Currently, I am only able to assess the differences between clusters 4-6 and 5-6 (pair comparison). Can you suggest any solution for it? Thank a lot!

**Comment by thdk13** [comment]
hi @jackbibby1,
I meant that when comparing across clusters 4, 5, and 6, I was unable to obtain the Fold Change value (only can get it through pair comparison). I still do not clearly understand, based on the qval, which pathway is more highly activated in a specific cluster. For instance, when using the plot_rank() function, we can observe that a pathway has a high rank of difference across clusters. However, it is challenging to point out which cluster has a higher activity score of that pathway compared to the others. It would be great if you help me to clarify this. thank you

**Comment by jackbibby1** [comment]
Ah yeah, you won't get a fold change value when there are more than 2 populations being compared. I just added the fold change calculation in the two-sample comparison as an extra bit of information. I would primarily focus on using the qval from SCPA anyway, and not the fold change, as outlined in the discussion [here](https://jackbibby1.github.io/SCPA/articles/interpreting_scpa_output.html#which-output-values-should-you-use). 

If you only want to know what pathways are the most differentially regulated across the clusters, then I would run the above multisample analysis and use the qval. But if you want to know which cluster shows the largest difference in a particular set of pathways, I would just choose a comparator cluster e.g. cluster 4, and then run cluster 4 vs 5 and 4 vs 6 in a two-sample comparison. Then I would use the qval output to tell you which pathway is the most differentially regulated across conditions. I would steer away from saying that a pathway has a 'higher activity' in a given condition, and rather interpret the qval as telling you what's differentially regulated across conditions. A lot of the time, a high qval will also mean that there's an enrichment of that pathway in a particular cluster, but sometimes it won't -- a pathway can have a high qval (differentially regulated), but no fold change. E.g. from the discussion above in the thread:

> If you're wanting to understand more about how SCPA generates it's results, I would encourage you to read our paper in [JASA](https://www.tandfonline.com/doi/full/10.1080/01621459.2020.1791131), or the discussion in our [Cell Reports paper](https://www.cell.com/cell-reports/fulltext/S2211-1247(22)01571-6#secsectitle0075). But briefly, something like the glycolysis pathway being stable in one condition (e.g. healthy) and highly variable in another (e.g. disease), even if there's not overall enrichment of the pathway in any condition, will be flagged by SCPA.

**Comment by thdk13** [comment]
Thank you so much for your informative answer. Now I understand it and thanks again for this useful package:)
