### ISSUE TITLE
Two questions...

### ISSUE THREAD

**Issue by hsiowa2** [jackbibby1/SCPA#63]
Hello, first of all, thank you for developing such an amazing tool for analyzing scRNAseq data. 

I have two questions :

1. As far as I understand, SCPA does not give pathway scores (as in the case of ssGSEA, GSVA etc.) as output, but gives the result of comparison between groups directly to the user.  Is there any output of SCPA the users can use access which is similar with pathway scores? Or is it inherently not reasonable to obtain them in SCPA method?
Edit : Would pathway_matrices() function could be the similar function I need?

2. Would SCPA be still working when you put bulk RNA-seq data as input as well?

Thank you very much.

**Comment by jackbibby1** [comment]
Hi,

Yup, you're right -- SCPA generates its p values by comparing pathway distributions in 2 or more samples/clusters, so it needs a comparator group. It means that you can't get a "most active" score with a single sample/cluster input as you can with some other tools. If you wanted to do this though, you could choose a single cluster as a comparator and then compare all other clusters to that one. This would give you a relative pathway activity for all the cell clusters, and tell you which pathways are the most different; similar to what we did in Figure 4K in [our paper](https://www.cell.com/cell-reports/pdfExtended/S2211-1247(22)01571-6).

The `pathway_matrices()` function just generates expression matrices for all your pathways and samples from your input, so this isn't a pathway score -- it's just your normalized expression values. It's more there in case it's a useful function for people wanting to plot expression of a pathway, and for SCPA to use internally.

SCPA will technically run with bulk RNA-seq data, but it isn't built for that, so I would stick to using it with single cell data (of any modality).

Jack

**Comment by hsiowa2** [comment]
Thank you! Regarding pathway_matrices() function, I asked the question after looking at Figure 4C in your paper. 

If we suppose that "Glycolysis" pathway consists of genes A, B, and C, then in Figure 4C the y-axis value of one red dot means the average values of gene expressions of A, B, and C from one single-cell. Did I understand correctly?

Thank you very much.

**Comment by jackbibby1** [comment]
Yup, that's correct. It's the average (column means) of that pathway per cell (represented by a red or green dot) arranged by pseudotime, where cells are in columns and genes are in rows. You can see the code to generate this [here](https://github.com/jackbibby1/scpa_paper/blob/2b50f0578e5150323f2148f0d4e732ab332d305c/figure_4.R#L11C1-L124C10) if that's any clearer. But yeah, you could also use the `pathway_matrices()` and then column means to generate the same thing.

The FC is a sum of fold changes (gene _a_ + gene _b_.... gene _k_) for all the genes of that pathway in one condition versus the other. You can read a bit more under the "Value" subheading when you run `?compare_pathways()`

**Comment by hsiowa2** [comment]
Thank you for your kind answer!
