### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ryshi06** [jackbibby1/SCPA#64]
**The specific error you're running into**
Either copy/paste the error message, or provide a screenshot

Downloading GitHub repo jackbibby1/SCPA@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/jackbibby1/SCPA/tarball/HEAD' failed

I have installed all the required packages manually and also tried to restart R, but I still cannot install this package. Can you give me some suggestions? Thank you!

**Comment by jackbibby1** [comment]
Hi,

Is there maybe an issue with internet speed -- someone else referenced a similar issue here: #62 

Jack
