### ISSUE TITLE
Input Data

### ISSUE THREAD

**Issue by AlexisFon** [jackbibby1/SCPA#65]
Hi, 

I have a question concerning the data used as input. When using Seurat, which is the slot used as input ? Is it "counts", "data" or "scale.data" ? And is there a way to modify that option ? 

Thanks in advance,

**Comment by jackbibby1** [comment]
Hi,

The `compare_seurat()` pulls data from the 'data' slot within whatever assay you choose. By default this is df@assays$RNA@data given this should be your normalized expression matrix. You can currently change the RNA part by specifying another assay e.g. `compare_seurat(..., assay = "integrated")`, but not the data slot.

Jack
