### ISSUE TITLE
installation of SCPA fails, because 'crossmatch' is unavailable.

### ISSUE THREAD

**Issue by MelanieRN** [jackbibby1/SCPA#70]
Unfortunately I can not install SCPA  because it has hard dependency on two packages that have been removed from CRAN on failure to correct reported errors:
https://cran.r-project.org/web/packages/crossmatch/index.html
https://cran.r-project.org/web/packages/multicross/index.html

**Comment by jackbibby1** [comment]
Hi,

You should be able to install these dependencies from CRAN archives by following the installation instructions here:

https://github.com/jackbibby1/SCPA?tab=readme-ov-file#installation

Just let me know if you're still having issues 

Jack

**Comment by MelanieRN** [comment]
Hi,

Thanks, I work in an environment where, unfortunately, it is not possible to install packages that have been actively removed from CRAN due to failure to address known problems. Are you planning to release an update that does not depend on these packages?

**Comment by MelanieRN** [comment]
Sounds great!
I found a temporarily solution, but I need a tar.gz file for the installation since I have to manually install the package to my workspace without internet connection (so I can not use the install_github command) where can I find the tar.gz file?

**Comment by jackbibby1** [comment]
Great -- just reopen the issue if there are any more problems
