### ISSUE TITLE
Error when installing: package 'multicross' is not available

### ISSUE THREAD

**Issue by r-melo** [jackbibby1/SCPA#71]
Hello,

I am trying to install SCPA and I get the error "package 'multicross' is not available". I saw in your to-do thread that one of the tasks is to incorporate archived CRAN packages. Is multicross on your list?

In the meantime, do you have a strategy to get SCPA installed?

Thank you for creating and maintaining the package.

**Comment by jackbibby1** [comment]
Hi,

Yeah -- that to do list was just to incorporate the crossmatch and multicross functions for people that aren't able to install them from CRAN archive (>99% of people will be able to install them from the archive though). SCPA should install fine if you install multicross like...

devtools::install_version("multicross", version = "2.1.0", repos = "http://cran.us.r-project.org")

As here: https://jackbibby1.github.io/SCPA/#installation

Let me know if you're still having issues

Jack

**Comment by r-melo** [comment]
Thank you for the information. That worked!

**Comment by Nessetti** [comment]
Hey Jack, 
I had to download multicross locally in order to get it to install, I was unable to install through devtools.
