### ISSUE TITLE
compare_seurat AND extract_seurat give error

### ISSUE THREAD

**Issue by francescopatane96** [jackbibby1/SCPA#72]
Hi! great package!

Today, after succesfully i had used SCPA during the last weeks, i encountered an error when using compare_seurat and extract_seurat functions: 

Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) : 
  invalid non-character version specification 'x' (type: double).

here my code after assigned cell types manually:

``
scpa_out <- compare_seurat(seurat,
                           group1 = "seurat_clusters", 
                           group1_population = "0",
                           pathways = pathways)
``

**Comment by jackbibby1** [comment]
Hi,

Yeah, I ran into this issue the other day -- I think there was some change in code on the Seurat side that caused it. I pushed an update to SCPA, so hopefully the newest version shouldn't have this error. Can you update SCPA and let me know if it's still happening?

Thanks
Jack

**Comment by francescopatane96** [comment]
thanks for the fast reply. i had updated the package and now i got this error: 

``
Extracting cells where condition == SP AND seurat_clusters == 1
Extracting data from the RNA assay
Extracting cells where condition == RR AND seurat_clusters == 1
Extracting data from the RNA assay
Processing in parallel using  cores

Cell numbers in population 1 = 1196
Cell numbers in population 2 = 1349
- If greater than 500 cells, these populations will be downsampled

Excluding 211 pathway(s) based on min/max genes parameter: WP_15Q112_COPY_NUMBER_VARIATION_SYNDROME, WP_ACETYLCHOLINE_SYNTHESIS, WP_ACE_INHIBITOR_PATHWAY, WP_ACQUIRED_PARTIAL_LIPODYSTROPHY_BARRAQUERSIMONS_SYNDROME, WP_ACTIVATION_OF_NLRP3_INFLAMMASOME_BY_SARSCOV2...

Calculating pathway fold changes...

Performing a two-sample analysis with SCPA...
Error in `dplyr::arrange()`:
ℹ In argument: `..1 = qval`.
Caused by error:
! object 'qval' not found
Backtrace:
  1. SCPA::compare_seurat(...)
  6. dplyr:::arrange.data.frame(., dplyr::desc(qval))
  7. dplyr:::arrange_rows(.data, dots = dots, locale = .locale)
  9. dplyr:::mutate.data.frame(data, `:=`("{name}", !!dot), .keep = "none")
 10. dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
 12. dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 13. mask$eval_all_mutate(quo)
 14. dplyr (local) eval()
Error in dplyr::arrange(., dplyr::desc(qval)) : 
Caused by error:
! object 'qval' not found
``

**Comment by francescopatane96** [comment]
p.s.  actually seurat_extract and compare_pathways functions does well while only compare_seurat shows the error i reported

**Comment by jackbibby1** [comment]
Hmm -- can you send me the code you're using to get this error so I have a bit more of an idea what's going on?

**Comment by francescopatane96** [comment]
`library(SCPA)
Hi Jack, here the code:
scpa_out <- compare_seurat(seurat,
                           group1 = "condition", 
                           group1_population = c("SP", "RR"),
                           group2 = "SingleRMonacopredMain",
                           group2_population = "T cells",
                           pathways = pathways, parallel = T)
`
where "condition" contains my ctr (RR) and treated (SP), and "SingleRMonacopredMain" contains cellular type annotations

**Comment by jackbibby1** [comment]
OK -- this should now be updated in SCPA version 1.6.2. I've made it so that if you specify parallel = TRUE with no cores argument, it defaults to 3 cores. Let me know if you're having any more issues

**Comment by francescopatane96** [comment]
Thank you very much :)
