### ISSUE TITLE
Extracting genes from scpa ouput

### ISSUE THREAD

**Issue by cdkodira** [jackbibby1/SCPA#74]
Is there a way to extract genes from the scpa output?
thanks

**Comment by jackbibby1** [comment]
Hi,

Are you wanting to extract genes from the pathways?

You can do this in msigdbr something like:

```
msigdbr("Homo sapiens", "H") %>%
   filter(gs_name == "HALLMARK_COMPLEMENT") %>%
   pull(gene_symbol)
```

If you want to know specific genes driving the signature then I'll direct you to [the discussion here](https://github.com/jackbibby1/SCPA/discussions/24#discussioncomment-4354254) and the links I mentioned

Jack
