### ISSUE TITLE
error x$Genes: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by INeedCNS** [jackbibby1/SCPA#76]
Hi,
I created my own gene set table as shown below, but I always encountered an error: error x$Genes: $ operator is invalid for atomic vectors. Same error  I used the combined_metabolic_pathways.csv you provided. However,  it worked correctly with the msigdbr pathways. What should I do?

str(pathways)
tibble [33 × 2] (S3: tbl_df/tbl/data.frame)
 $ Pathway: chr [1:33] "CCL" "CCL" "CCL" "CCL" ...
 $ Genes  : chr [1:33] "Ccl1" "Ccl2" "Ccl3" "Ccl4" ...

```
scpa_out <- compare_pathways(samples = list(resting, activated), 
                             pathways = pathways)

Using single core processing. Specify 'parallel = TRUE' and `cores = x` arguments for parallel processing

Cell numbers in population 1 = 2328
Cell numbers in population 2 = 4057
- If greater than 500 cells, these populations will be downsampled

error x$Genes: $ operator is invalid for atomic vectors
```

**Comment by jackbibby1** [comment]
Hi,

Can you try running:

```
scpa_out <- compare_pathways(samples = list(resting, activated), 
                             pathways = list(pathways))
```

Jack
