### ISSUE TITLE
Interpreting and reporting significant Qvalues

### ISSUE THREAD

**Issue by MAGBP** [jackbibby1/SCPA#77]
@jackbibby1 

Hi Jack
Using SCPA for a publication! I was wondering what you would recommend in terms of a "cut-off" value for reporting significant change in distribution of pathways for the Qvalues. I cannot seem to find definitive explanation of this; when would you say Qvalues represent:

1: no to little significant change
2: significant to moderate change
3: moderate to high change

I am comparing baseline and follow up samples after therapeutic intervention

**Comment by jackbibby1** [comment]
Hi,

Great. The Qval stat was discussed a bit [here](https://github.com/jackbibby1/SCPA/discussions/48). It's basically just a transformed adjusted pval that makes things easy to plot and report. In general, a qval > 2 represents a significant change in pathway behaviour, though likely still small at this point. Then the larger you go, the larger the change will be. If you wanted to bin the results into some quasi-meaningful categories, I'd say something like:

No change = qval < 2
Small change = qval 2-4
Medium change = qval > 4-8
Large change = qval > 8

There's an obvious and very large caveat here that this doesn't really tie to anything tangible apart from my experience in using SCPA a lot and doing some in vitro validations based on these cutoffs. I would just recommend ranking the qvals and judging their relevance based on those rankings

Jack

**Comment by MAGBP** [comment]
Thank you for swift reply!
