### ISSUE TITLE
Trying to retrive the genes that are being used for each pathway in SCPA compare_pathways

### ISSUE THREAD

**Issue by yowe21** [jackbibby1/SCPA#82]
Hello,

I am executing compare_pathways on a Seurat object, and it works great. Now, we are trying to see which genes are being used from our Seurat object to examine and compare each pathway. We cannot find a way to retrieve this information from the output. Is there a way to retrieve this information from the package? 
Please let me know if you need future clarification!
Thank you ahead of time!

**Comment by jackbibby1** [comment]
Hi,

Any gene that's expressed in the pathway will be used in SCPA, so you can just pull all the genes of the pathway from wherever you're using them e.g.

```
msigdbr("Homo sapiens", "H") %>%
  filter(gs_name == "HALLMARK_GLYCOLYSIS") %>%
  pull(gene_symbol)
```

or if you want multiple pathways:

```
pathways <- c("HALLMARK_GLYCOLYSIS", "HALLMARK_COMPLEMENT", "KEGG_JAK_STAT_SIGNALING_PATHWAY")
msigdbr("Homo sapiens") %>%
  filter(gs_name %in% pathways) %>%
  SCPA::format_pathways()
```

Jack

**Comment by yowe21** [comment]
Thank you so much for your help and for creating such a useful tool!
