### ISSUE TITLE
Issue running "compare_pathways" in SCPA

### ISSUE THREAD

**Issue by ginamcneill** [jackbibby1/SCPA#83]
**The specific error you're running into**
Error in x$Genes : $ operator is invalid for atomic vectors

**To Reproduce**
The code to reproduce the error e.g.

```
library(SCPA)
library(Seurat)
library(tidyverse)
library(readr)
load("~/Objects/organoids.RData")
pathways <- read_csv("combined_metabolic_pathways.csv")

low <- seurat_extract(organoids,
                          meta1 = "celltype", value_meta1 = "cCTB",
                          meta2 = "Oxygen", value_meta2 = "Low")

high <- seurat_extract(organoids,
                            meta1 = "celltype", value_meta1 = "cCTB",
                          meta2 = "Oxygen", value_meta2 = "High")

high_low <- compare_pathways(samples = list(high, low), 
                             pathways = pathways)
```

**Expected behavior**
SCPA object output

**Additional context**
I downloaded the T cell dataset used in the tutorial (https://jackbibby1.github.io/SCPA/articles/comparing_two_populations.html) to see if the issue may have been with my data but I got the same error message with the T cell data as well when running "compare_pathways". I also tried making my "high" and "low" matrices into data frames so that they were no longer atomic vectors but that also didn't work. I also tried running the "compare_seurat" function from a different SCPA tutorial and ran into a similar error "Error in x$Pathway : $ operator is invalid for atomic vectors".

Thanks in advance for your help!

**Comment by jack-bibby** [comment]
Hi,

This looks like an issue with the pathways. You need to format these before input into `compare_pathways()`.

Can you see this page: https://jackbibby1.github.io/SCPA/articles/using_gene_sets.html and let me know if you're still having issues?

Jack

**Comment by ginamcneill** [comment]
Hi Jack,

Thanks for the reply. I have taken a screenshot of the excel file I am using for the "pathways" which I downloaded from (https://github.com/jackbibby1/SCPA/tree/main/gene_sets). Correct me if I am wrong but it looks the same as the last screenshot on this page (https://jackbibby1.github.io/SCPA/articles/using_gene_sets.html). 

Thanks,

Gina


<img width="1440" alt="Screenshot 2024-10-10 at 8 06 11 AM" src="https://github.com/user-attachments/assets/711b0fb8-ffe5-4ba6-ae26-7b274c1fdf23">

**Comment by jack-bibby** [comment]
Hi Gina,

Yup, that's right, but you either need to just supply the filepath to it i.e.

```
scpa_out <- compare_pathways(..., pathways = "filepath/to/csv")
```

or first run `format_pathways()` on the R object i.e.

```
pathways <- read.csv(...) %>% format_pathways()
scpa_out <- compare_pathways(..., pathways = pathways)
```

Jack

**Comment by ginamcneill** [comment]
Running scpa_out <- compare_pathways(..., pathways = "filepath/to/csv") worked, thanks so much for your help and also for making a cool package!
