### ISSUE TITLE
ERROR: dependency ‘multicross’ is not available for package ‘SCPA’

### ISSUE THREAD

**Issue by monisha1202** [jackbibby1/SCPA#84]
**"multicross" package needed for SCPA which has been removed from CRAN**

multicross package info:
https://cran.r-project.org/web/packages/multicross/index.html

I tried installing the archived version but it is not compatible with later versions of R. Is there any workaround for that?

```
> devtools::install_version("multicross", version = "2.1.0", repos = "http://cran.us.r-project.org")
Warning: unable to access index for repository http://cran.us.r-project.org/src/contrib:
  cannot open URL 'http://cran.us.r-project.org/src/contrib/PACKAGES'
Error in download_version_url(package, version, repos, type) : 
  couldn't find package 'multicross'
```

Thank You.

**Comment by jack-bibby** [comment]
Hi,

Have you tried the instructions here: https://github.com/jackbibby1/SCPA?tab=readme-ov-file#installation

The installation runs fine from my end and I'm on R version 4.4.0

Jack

**Comment by monisha1202** [comment]
Thank you for quick response.

I am on R version 4.3.3 (2024-02-29) and it throws the error: 

```
Warning: unable to access index for repository http://cran.us.r-project.org/src/contrib:
  cannot open URL 'http://cran.us.r-project.org/src/contrib/PACKAGES'
Error in download_version_url(package, version, repos, type) : 
  couldn't find package 'multicross'
```

**Comment by jackbibby1** [comment]
Hi,

This may be an issue with a CRAN mirror. Can you try running:

```
devtools::install_version("multicross", version = "2.1.0", repos = "http://cloud.r-project.org")
```

Jack

**Comment by monisha1202** [comment]
I am still getting the same error. I tried restarting my R session as well.

Thanks.

**Comment by jackbibby1** [comment]
Hmm, tough to say -- everything works fine from my end on R v4.4. Could you try this?

https://stackoverflow.com/questions/72619247/warning-in-install-packages-unable-to-access-index-for-repository
